### ISSUE TITLE
Problem with han toolbox 0.4

### ISSUE THREAD

**Issue by Strikerz99** [nikolaevich23/han-toolbox-mod#1]
I update han toolbox and then install han toolbox mod but it doesn't work update it to work with new version, it's very usefull instead the old

**Comment by nikolaevich23** [comment]
our product its fork, we dnt support original han toolbox

**Comment by Strikerz99** [comment]
can you fork the 4.0?

2018-04-03 11:56 GMT+02:00 nikolaevich23 <notifications@github.com>:

**Comment by nikolaevich23** [comment]
see update
