### ISSUE TITLE
Alternative for CFW Users

### ISSUE THREAD

**Issue by LuanTeles** [nikolaevich23/han-toolbox-mod#2]
Can you make a version that support background download for the cfw users
using the 
<Pair key="module_name"><String>webrender_plugin</String></Pair>			
<Pair key="module_action"><String>http://localhost/install.ps3?url=xxxx</String></Pair>
			
thanks in advance

**Comment by LuanTeles** [comment]
Also psp , psx and ps2 categories for its content on psn

**Comment by nikolaevich23** [comment]
XMB dnt support to many links, so no. But for CFW have alternative programm. Example http://store.brewology.com/ahomebrew.php?brewid=295

**Comment by LuanTeles** [comment]
Yeap i know but its outdated and doent support full games and etc , you could do a mod of it?

it's also a good ideia to add inside the game the download link ( already has) and a Rap link for activation.
